### ISSUE TITLE
Monospace font is not centered in height

### ISSUE THREAD

**Issue by Maaxxs** [manuel-tiedtke/M2N-Webanwendungen-2#2]
In the `index.html` the text `Read more` and `Let's go` in the buttons is not really centered. 

The padding of 6px to top and bottom seems correct. Is this a font issue?

**Comment by DrNochi** [comment]
Yes, it seems that this is a font issue -- actually, it is an issue on Bootstrap's side... :/

If the button font is changed to the default monospaced font with `font-family: monospace`, the text appears centered, but if the Bootstrap CSS class `text-monospace` is used, the off-centering occurs.
It looks like some the monospace fonts prefered by Bootstrap have this issue.

**Comment by Maaxxs** [comment]
not relevant anymore.
